apiVersion: v1
kind: Namespace
metadata:
  name: tlse-pr-${PR_NUMBER}
  labels:
    name: tlse-pr-${PR_NUMBER}
---
apiVersion: v1
kind: Secret
metadata:
  name: container-registry
  namespace: tlse-pr-${PR_NUMBER}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "${CONTAINER_REGISTRY_USER}",
          "password": "${CONTAINER_REGISTRY_PASSWORD}"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tlse-frontend
  namespace: tlse-pr-${PR_NUMBER}
  labels:
    app: tlse-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tlse-frontend
  template:
    metadata:
      labels:
        app: tlse-frontend
    spec:
      containers:
        - name: tlse-frontend
          image: ghcr.io/thenativeweb/tlse-frontend:pr-${PR_NUMBER}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
          imagePullPolicy: "Always"
      imagePullSecrets:
        - name: docker-container-registry
---
kind: Service
apiVersion: v1
metadata:
  name: tlse-frontend
  namespace: tlse-pr-${PR_NUMBER}
  labels:
    app: tlse-frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: tlse-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tlse-frontend
  namespace: tlse-pr-${PR_NUMBER}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - secretName: thenativeweb-io-frontend
      hosts:
        - pr-${PR_NUMBER}.gitops.tlse.thenativeweb.io
  rules:
    - host: pr-${PR_NUMBER}.gitops.tlse.thenativeweb.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tlse-frontend
                port:
                  name: http
