version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - dotKuro
      - yeldiRium
    # For semantic release
    commit-message:
      prefix: fix
      prefix-development: chore
